Account Abstraction P2P AA0
NethermindEth/mev-aa-geth pull request #12
Opened 2022-03-09 03:32 UTC by jmederosalvarado

Version zero of account abstraction p2p protocol. Most of the code structure takes inspiration from the `eth` and `snap` protocol implementations within this repo.

2022-03-09 09:30 UTC, kristofgazso requested changes
very very nice edit!

overall q: do we need to copy-paste so much functionality from the vanilla p2p logic? isn't there a way to apply more DRY?

2022-03-09 09:30 UTC, kristofgazso commented on core/types/userop.go
> +	ChainId            *big.Int `rlp:"-"`
feels a bit weird having chainId and entryPoint in the userOp struct, but its okay if its unavoidable

2022-03-09 09:30 UTC, kristofgazso commented on core/userop_pool.go
> +	opFeed       event.Feed
why is this in the mev pool instead of in the op pool?

2022-03-09 09:30 UTC, kristofgazso commented on eth/handler.go
> +	// Get retrieves the transaction from local userop pool with given
minor: it retrieves the op, not the tx

2022-03-09 09:30 UTC, kristofgazso commented on eth/handler_aa.go
> +		h.oppool.AddUserOp(op)
question: would it be worth making this async?

2022-03-09 09:30 UTC, kristofgazso commented on eth/peerset.go
> +// transaction in their set of known hashes.
minor: op not tx

2022-03-09 09:30 UTC, kristofgazso commented on eth/protocols/aa/broadcast.go
> +			queue = queue[:copy(queue, queue[hashesCount:])]
do we need to copy?

2022-03-09 09:30 UTC, kristofgazso commented on eth/protocols/aa/handler.go
> +type UserOpPool interface {
why do we redifine the pool interface? why not just use the original one?

2022-03-09 09:30 UTC, kristofgazso commented on eth/protocols/aa/handlers.go
> +func handleUserOps(backend Backend, msg Decoder, peer *Peer) error {
minor: do we need a seperate file for this func?

2022-03-09 09:30 UTC, kristofgazso commented on eth/protocols/aa/peer.go
> +// AsyncSendUserOps queues a list of transactions (by hash) to eventually
minor: ops not txs

2022-03-09 14:21 UTC, jmederosalvarado commented on eth/handler_aa.go
> +		h.oppool.AddUserOp(op)
Actually I didn't worry too much about because in order to implement a future v1 of the spec, that includes NewPooledUserOps and GetPooledUserOps messages we will need to add a userop fetcher data structure before the userop pool, and that woul be async. This data structure could also solve a few issues right now, like performing a few static checks, so I think it would be better to just add the data structure now than making this loop async.

2022-03-09 14:32 UTC, jmederosalvarado commented on eth/protocols/aa/handlers.go
> +func handleUserOps(backend Backend, msg Decoder, peer *Peer) error {
This is because of the v1 I referred to above, I'm trying to leave everything ready for such v1, I think there's no real "going to production" without it, the current p2p approach would overload the network when AA becomes a standard

2022-03-09 14:38 UTC, jmederosalvarado commented on eth/protocols/aa/handler.go
> +type UserOpPool interface {
Mainly two reasons:

1. Golang doesn't allow cycling imports, so importing the pool interface from eth.handler is not an option

2. I think it's idiomatic in go (and in general good design) that each package/struct (or any piece of code that provides a "self contained" functionality) to put everything they depend on behind an interface with the exact methods they'll need, this way a user of the functionality would know exactly the requisites of what they need to pass in, and these would not be incremented by any othe logic than the one the user is trying to use.

The fact that they have the same name shouldn't mean anything. It's duck typing with static types.

For instance if someone were to test this handler they would only need to pass an object with a `Get` method to act as the `UserOpPool`, and they wouldn't need to pass other methods that are only relevant when you are testing functionality in `eth/handler`

2022-03-09 17:10 UTC, jmederosalvarado commented on core/types/userop.go
> +	ChainId            *big.Int `rlp:"-"`
reasoning behind this is the folowing is: having chainid here simplifies a lot computing the requestid from everwhere (this is done a lot in `mev-aa-geth`), I think of user ops as a "higher level" transaction, and transactions have a field to store the chainid, so it also feels natural to have that field here.

2022-03-09 17:26 UTC, jmederosalvarado commented on eth/protocols/aa/broadcast.go
> +			queue = queue[:copy(queue, queue[hashesCount:])]
yes, the thing is that if you don't copy then you're keeping a reference to a slice of an array which might have increase its capacity tremendously, thus ocuppying a lot of memory, even if the slice is only pointing to a constant size portion of such array, the array backing the slice would increase its capacity and memory consumption. the copy ensures that we have a new array with the minimum necessary capacity to fit our data, so that we let the garbage collector take care of the old potentially too big array.

2022-03-09 17:34 UTC, jmederosalvarado commented
> do we need to copy-paste so much functionality from the vanilla p2p logic? isn't there a way to apply more DRY?

There two types of repetition in this PR, some of it are just look unnecessary right now, but it is just me preparing the ground for an update on the p2p spec, so the boilerplate is to have some level of extensibility. The more important type is in some data structures that are being copied to be reused, this is bad, and I've had to do it a few times in the codebase, the reason is that this data structures or functionality is either not being exported from the package defining them or are not implemented to work with diff data types (sometimes bc of not having generics). a possible fix is to change this myself and start exporting what I need, but I'm afraid this would be a problem if we intend to merge upstream and it could even make it difficult for us to get updates from upstream.

2022-03-12 18:10 UTC, kristofgazso commented on core/userop_pool.go
> +	opFeed       event.Feed
ah my bad, thought it was another file

2022-03-12 18:13 UTC, kristofgazso approved these changes
esketit

2022-03-12 18:13 UTC, merged